import { Providers } from './providers'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import { Navbar, NavbarBrand } from '@nextui-org/react'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className} style={{width: '100vw', height: '100vh'}}>
        <Providers>
        <Navbar position="static">
          <NavbarBrand>VERA Dispatcher</NavbarBrand>
        </Navbar>
        <main style={{width: '100%', height: '100%'}}>
          {children}
        </main>
        </Providers>
      </body>
    </html>
  )
}
