// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0-devel
// 	protoc        v3.14.0
// source: alert_api_gateway.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AlertSubscriptionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlertRecipientId string `protobuf:"bytes,1,opt,name=alert_recipient_id,json=alertRecipientId,proto3" json:"alert_recipient_id,omitempty"`
}

func (x *AlertSubscriptionRequest) Reset() {
	*x = AlertSubscriptionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_api_gateway_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertSubscriptionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertSubscriptionRequest) ProtoMessage() {}

func (x *AlertSubscriptionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_api_gateway_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertSubscriptionRequest.ProtoReflect.Descriptor instead.
func (*AlertSubscriptionRequest) Descriptor() ([]byte, []int) {
	return file_alert_api_gateway_proto_rawDescGZIP(), []int{0}
}

func (x *AlertSubscriptionRequest) GetAlertRecipientId() string {
	if x != nil {
		return x.AlertRecipientId
	}
	return ""
}

type AlertAcknowledgementRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlertRecipientId string `protobuf:"bytes,1,opt,name=alert_recipient_id,json=alertRecipientId,proto3" json:"alert_recipient_id,omitempty"`
	AlertId          string `protobuf:"bytes,2,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
}

func (x *AlertAcknowledgementRequest) Reset() {
	*x = AlertAcknowledgementRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_api_gateway_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertAcknowledgementRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertAcknowledgementRequest) ProtoMessage() {}

func (x *AlertAcknowledgementRequest) ProtoReflect() protoreflect.Message {
	mi := &file_alert_api_gateway_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertAcknowledgementRequest.ProtoReflect.Descriptor instead.
func (*AlertAcknowledgementRequest) Descriptor() ([]byte, []int) {
	return file_alert_api_gateway_proto_rawDescGZIP(), []int{1}
}

func (x *AlertAcknowledgementRequest) GetAlertRecipientId() string {
	if x != nil {
		return x.AlertRecipientId
	}
	return ""
}

func (x *AlertAcknowledgementRequest) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

type AlertAcknowledgementResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *AlertAcknowledgementResponse) Reset() {
	*x = AlertAcknowledgementResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_api_gateway_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlertAcknowledgementResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlertAcknowledgementResponse) ProtoMessage() {}

func (x *AlertAcknowledgementResponse) ProtoReflect() protoreflect.Message {
	mi := &file_alert_api_gateway_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlertAcknowledgementResponse.ProtoReflect.Descriptor instead.
func (*AlertAcknowledgementResponse) Descriptor() ([]byte, []int) {
	return file_alert_api_gateway_proto_rawDescGZIP(), []int{2}
}

type Assignment struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Assignment) Reset() {
	*x = Assignment{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_api_gateway_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Assignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Assignment) ProtoMessage() {}

func (x *Assignment) ProtoReflect() protoreflect.Message {
	mi := &file_alert_api_gateway_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Assignment.ProtoReflect.Descriptor instead.
func (*Assignment) Descriptor() ([]byte, []int) {
	return file_alert_api_gateway_proto_rawDescGZIP(), []int{3}
}

type Alert struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AlertId    string      `protobuf:"bytes,1,opt,name=alert_id,json=alertId,proto3" json:"alert_id,omitempty"`
	Assignment *Assignment `protobuf:"bytes,2,opt,name=assignment,proto3" json:"assignment,omitempty"`
}

func (x *Alert) Reset() {
	*x = Alert{}
	if protoimpl.UnsafeEnabled {
		mi := &file_alert_api_gateway_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_alert_api_gateway_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_alert_api_gateway_proto_rawDescGZIP(), []int{4}
}

func (x *Alert) GetAlertId() string {
	if x != nil {
		return x.AlertId
	}
	return ""
}

func (x *Alert) GetAssignment() *Assignment {
	if x != nil {
		return x.Assignment
	}
	return nil
}

var File_alert_api_gateway_proto protoreflect.FileDescriptor

var file_alert_api_gateway_proto_rawDesc = []byte{
	0x0a, 0x17, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x67, 0x61, 0x74, 0x65,
	0x77, 0x61, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x10, 0x76, 0x65, 0x72, 0x61, 0x2e,
	0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x48, 0x0a, 0x18, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x5f, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x10, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69,
	0x65, 0x6e, 0x74, 0x49, 0x64, 0x22, 0x66, 0x0a, 0x1b, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x41, 0x63,
	0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x12, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x72, 0x65,
	0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x10, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x52, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74,
	0x49, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x49, 0x64, 0x22, 0x1e, 0x0a,
	0x1c, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x0c, 0x0a,
	0x0a, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0x60, 0x0a, 0x05, 0x41,
	0x6c, 0x65, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x49, 0x64, 0x12,
	0x3c, 0x0a, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e,
	0x74, 0x52, 0x0a, 0x61, 0x73, 0x73, 0x69, 0x67, 0x6e, 0x6d, 0x65, 0x6e, 0x74, 0x32, 0xe1, 0x01,
	0x0a, 0x0c, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c,
	0x0a, 0x11, 0x53, 0x75, 0x62, 0x73, 0x63, 0x72, 0x69, 0x62, 0x65, 0x54, 0x6f, 0x41, 0x6c, 0x65,
	0x72, 0x74, 0x73, 0x12, 0x2a, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x53, 0x75, 0x62, 0x73,
	0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x22, 0x00, 0x30, 0x01, 0x12, 0x73, 0x0a, 0x10,
	0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x41, 0x6c, 0x65, 0x72, 0x74,
	0x12, 0x2d, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x2e, 0x2e, 0x76, 0x65, 0x72, 0x61, 0x2e, 0x61, 0x6c, 0x65, 0x72, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x2e, 0x41, 0x6c, 0x65, 0x72, 0x74, 0x41, 0x63, 0x6b, 0x6e, 0x6f, 0x77, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22,
	0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_alert_api_gateway_proto_rawDescOnce sync.Once
	file_alert_api_gateway_proto_rawDescData = file_alert_api_gateway_proto_rawDesc
)

func file_alert_api_gateway_proto_rawDescGZIP() []byte {
	file_alert_api_gateway_proto_rawDescOnce.Do(func() {
		file_alert_api_gateway_proto_rawDescData = protoimpl.X.CompressGZIP(file_alert_api_gateway_proto_rawDescData)
	})
	return file_alert_api_gateway_proto_rawDescData
}

var file_alert_api_gateway_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_alert_api_gateway_proto_goTypes = []interface{}{
	(*AlertSubscriptionRequest)(nil),     // 0: vera.alert.proto.AlertSubscriptionRequest
	(*AlertAcknowledgementRequest)(nil),  // 1: vera.alert.proto.AlertAcknowledgementRequest
	(*AlertAcknowledgementResponse)(nil), // 2: vera.alert.proto.AlertAcknowledgementResponse
	(*Assignment)(nil),                   // 3: vera.alert.proto.Assignment
	(*Alert)(nil),                        // 4: vera.alert.proto.Alert
}
var file_alert_api_gateway_proto_depIdxs = []int32{
	3, // 0: vera.alert.proto.Alert.assignment:type_name -> vera.alert.proto.Assignment
	0, // 1: vera.alert.proto.AlertService.SubscribeToAlerts:input_type -> vera.alert.proto.AlertSubscriptionRequest
	1, // 2: vera.alert.proto.AlertService.AcknowledgeAlert:input_type -> vera.alert.proto.AlertAcknowledgementRequest
	4, // 3: vera.alert.proto.AlertService.SubscribeToAlerts:output_type -> vera.alert.proto.Alert
	2, // 4: vera.alert.proto.AlertService.AcknowledgeAlert:output_type -> vera.alert.proto.AlertAcknowledgementResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_alert_api_gateway_proto_init() }
func file_alert_api_gateway_proto_init() {
	if File_alert_api_gateway_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_alert_api_gateway_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertSubscriptionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_api_gateway_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertAcknowledgementRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_api_gateway_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlertAcknowledgementResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_api_gateway_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Assignment); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_alert_api_gateway_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Alert); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_alert_api_gateway_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_alert_api_gateway_proto_goTypes,
		DependencyIndexes: file_alert_api_gateway_proto_depIdxs,
		MessageInfos:      file_alert_api_gateway_proto_msgTypes,
	}.Build()
	File_alert_api_gateway_proto = out.File
	file_alert_api_gateway_proto_rawDesc = nil
	file_alert_api_gateway_proto_goTypes = nil
	file_alert_api_gateway_proto_depIdxs = nil
}
